[project]
name = "langchain-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "httpx-sse>=0.4.3",
    "langchain>=1.0.3",
    "langchain-community>=0.4.1",
    "langchain-deepseek>=1.0.0",
    "nodebook>=0.3.1",
    "notebook>=7.4.7",
    "pyjwt>=2.10.1",
]
